---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-runner
  namespace: external-secrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rds-config
  namespace: external-secrets
data:
  AWS_REGION: "us-east-1"
  TF_STATE_BUCKET: "sp-01102026-aws-kub"
  TF_STATE_KEY: "rds/terraform.tfstate"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: rds-deployer
  namespace: external-secrets
spec:
  template:
    spec:
      serviceAccountName: terraform-runner
      initContainers:
      - name: git-cloner
        image: alpine/git
        args: ["clone", "https://github.com/sprakriy/aws-hybrid-project.git", "/src"]
        volumeMounts:
        - name: code
          mountPath: /src
      containers:
      - name: terraform-executor
        image: hashicorp/terraform:latest
        workingDir: /src  # This tells Terraform: "Look here for rds.tf"
        env:
        - name: TF_VAR_db_username
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: TF_VAR_db_password
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        envFrom:
        - configMapRef:
            name: rds-config
        - secretRef:
            name: aws-creds
        command: ["/bin/sh", "-c"]
        args:
          - |
            terraform init \
              -backend-config="bucket=${TF_STATE_BUCKET}" \
              -backend-config="key=${TF_STATE_KEY}" \
              -backend-config="region=${AWS_REGION}"
            terraform apply -auto-approve
        volumeMounts:
        - name: code
          mountPath: /src
      restartPolicy: Never
      volumes:
      - name: code
        emptyDir: {}